{"timestamp":"2025-05-31T23:30:28.766458","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-05-31T23:30:28.766934","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/projeto1/projeto1.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-05-31T23:30:28.938686","level":"info","event":"Secrets backends loaded for worker","count":1,"backend_classes":["EnvironmentVariablesBackend"],"logger":"supervisor"}
{"timestamp":"2025-05-31T23:30:28.953916","level":"info","event":"Connection Retrieved 'minioS3'","logger":"airflow.hooks.base"}
{"timestamp":"2025-05-31T23:30:28.954081","level":"info","event":"AWS Connection (conn_id='minioS3', conn_type='aws') credentials retrieved from login and password.","logger":"airflow.providers.amazon.aws.utils.connection_wrapper.AwsConnectionWrapper"}
{"timestamp":"2025-05-31T23:30:29.448100","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"S3UploadFailedError","exc_value":"Failed to upload ./data/projeto_postgres/projeto_postgres_1.parquet to airflow/./projeto_postgres/projeto_postgres_1.parquet: An error occurred (XMinioInvalidResourceName) when calling the PutObject operation: Resource name contains bad components such as \"..\" or \".\".","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":838,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1130,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/projeto1/projeto1.py","lineno":63,"name":"insert_minio"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py","lineno":153,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py","lineno":126,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py","lineno":1129,"name":"load_file"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/boto3/s3/inject.py","lineno":145,"name":"upload_file"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/boto3/s3/transfer.py","lineno":378,"name":"upload_file"}]},{"exc_type":"ClientError","exc_value":"An error occurred (XMinioInvalidResourceName) when calling the PutObject operation: Resource name contains bad components such as \"..\" or \".\".","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/boto3/s3/transfer.py","lineno":372,"name":"upload_file"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/s3transfer/futures.py","lineno":103,"name":"result"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/s3transfer/futures.py","lineno":264,"name":"result"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/s3transfer/tasks.py","lineno":135,"name":"__call__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/s3transfer/tasks.py","lineno":158,"name":"_execute_main"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/s3transfer/upload.py","lineno":796,"name":"_main"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py","lineno":569,"name":"_api_call"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py","lineno":1023,"name":"_make_api_call"}]}]}
